# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a01c0a89b124f6d8955e109c34b135560cb1eacd29221d963d42eb7e5988333529771d1a7f2ec11e2262899994d133c1d56e37de1c0a78202f07854e4743bfd8

test:
  secret_key_base: 2f7bffc02655c4d9c0547facf4370bf294cafe260b9c42e258f4b74c517a318ca7566abafd13d6466b84f4889769321a3840121cc87bc94f5a4cf0458d6978e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
